fixtures:
  symlinks:
    monit: "#{source_dir}"
  forge_modules:
    epel:
      repo: "stahnma/epel"
      ref: "1.3.1"
    firewall:
      repo: "puppetlabs/firewall"
      ref: "2.0.0"
    os:
      repo: "puppetfinland/os"
      ref: "1.1.3"
    packetfilter:
      repo: "puppetfinland/packetfilter"
      ref: "2.0.3"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.25.1"
    yumrepo:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.0.6"
